[tool.poetry]
name = "todos"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
<<<<<<< HEAD
python = "^3.8"
=======
python = "^3.11.10"
>>>>>>> b50d7d1 (Create new directory for todo_list app)
flask = "^3.0.0"
gunicorn = "^21.2.0"
uuid = "^1.30"

<<<<<<< HEAD

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
=======
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
>>>>>>> b50d7d1 (Create new directory for todo_list app)
